# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    default_config: custom_config
    base_path: 'build/ckeditor'
    js_path: 'build/ckeditor/ckeditor.js'
    configs:
        custom_config:
            toolbar:
                - {
                    items: [
                        'Bold', 'Italic', 'Underline',
                        '-',
                        'Cut', 'Copy', 'Paste', 'Undo', 'Redo',
                        '-',
                        'Link',
                        '-',
                        'NumberedList', 'BulletedList',
                    ]
                }
