vich_uploader:
    db_driver: orm

    mappings:
        music_sheets:
            uri_prefix: /uploads/music-sheets
            upload_destination: '%kernel.project_dir%/public/uploads/music-sheets'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            # BUG : despite putting the following options, files won't be deleted on entity update or remove
            delete_on_update: true
            delete_on_remove: true
